import { describe, expect, test } from "@jest/globals";
import { Solution } from "./solution";

describe("Advent of Code Day 2: Gift Shop (General Invalid Product IDs)", () => {
  // The required sum for the example input, based on the rule that IDs are invalid if
  // they consist of a sequence of digits repeated 2 or more times (P^n, n >= 2).
  const EXAMPLE_INPUT_SUM = 4174379265;

  test("Provided Example 1 (P repeated >= 2 times)", () => {
    /*
     * This example covers various repeat types: P^2, P^3, P^4, etc.
     * The input ranges are processed independently, and IDs found in overlapping
     * ranges must be counted multiple times.
     */
    const exampleInput = `11-22,95-115,998-1012,1188511880-1188511890,222220-222224,1698522-1698528,446443-446449,38593856-38593862,565653-565659,824824821-824824827,2121212118-2121212124`;

    const solver = new Solution();
    expect(solver.solve(exampleInput)).toBe(EXAMPLE_INPUT_SUM);
  });

  describe("Boundary Conditions and Repeat Types", () => {
    test("Two-repeat (P^2) case - Smallest ID", () => {
      // Range: 11-20. Invalid ID: 11 (P=1, n=2). Sum: 11.
      const input = `11-20`;
      expect(new Solution().solve(input)).toBe(11);
    });

    test("Three-repeat (P^3) case - Starting Boundary", () => {
      // Range: 111-120. Invalid ID: 111 (P=1, n=3). Sum: 111.
      const input = `111-120`;
      expect(new Solution().solve(input)).toBe(111);
    });

    test("Range covering P^3 and P^2 IDs (222)", () => {
      // Range: 110-223. Invalid IDs: 111 (P=1, n=3), 222 (P=2, n=3).
      // Sum: 111 + 222 = 333.
      const input = `110-223`;
      expect(new Solution().solve(input)).toBe(333);
    });

    test("Complex overlap where one ID is found by multiple patterns (P^2 and P^4)", () => {
      // Range: 1111-1222.
      // 1111 is generated by: P=1, n=4 (1 repeated 4 times) AND P=11, n=2 (11 repeated 2 times).
      // IDs within a single range must be counted only once.
      // Invalid IDs: 1111. Sum: 1111.
      const input = `1111-1222`;
      expect(new Solution().solve(input)).toBe(2323);
    });

    test("Four-repeat (P^4) case", () => {
      // Range: 4440-4450. Invalid ID: 4444. Sum: 4444.
      const input = `4440-4450`;
      expect(new Solution().solve(input)).toBe(4444);
    });

    test("Required Multiple Counting of IDs across different ranges", () => {
      // Range 1: 11-11 (Invalid ID: 11)
      // Range 2: 11-11 (Invalid ID: 11)
      // Total Sum: 11 + 11 = 22.
      const input = `11-11, 11-11`;
      expect(new Solution().solve(input)).toBe(22);
    });

    test("Range limit check: invalid ID just outside the range", () => {
      // Invalid ID 1212 is outside 1213-1250. Sum: 0.
      const input = `1213-1250`;
      expect(new Solution().solve(input)).toBe(0);
    });
  });

  describe("Edge Cases and Input Format Issues", () => {
    test("Zero handling: The smallest valid ID must be 11 (P=1, n=2)", () => {
      // Range: 1-10. Sum: 0.
      const input = `1-10`;
      expect(new Solution().solve(input)).toBe(0);
    });

    test("Empty input should result in zero", () => {
      expect(new Solution().solve("")).toBe(0);
    });

    test("Input with unexpected formatting (extra spaces, tabs, newline)", () => {
      // Range: 11-22 (11, 22), 99-99 (99). Sum: 11 + 22 + 99 = 132.
      const messyInput = ` 11 - 22 ,	
			99 - 99, `;
      expect(new Solution().solve(messyInput)).toBe(132);
    });

    test("Inverted range (start > end)", () => {
      const input = `20-11`;
      expect(new Solution().solve(input)).toBe(0);
    });
  });
});
